# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 10:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('money', '0004_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialog_id', models.CharField(max_length=30)),
                ('conversation_id', models.CharField(max_length=30)),
                ('client_id', models.CharField(max_length=30)),
                ('fk_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
