# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 08:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userextras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('street_no', models.IntegerField(default=0)),
                ('street', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('spending', models.IntegerField(default=0)),
                ('income', models.IntegerField(default=0)),
                ('primary_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='primary_key',
        ),
        migrations.DeleteModel(
            name='user_info',
        ),
    ]
