# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 08:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('max_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('duration', models.CharField(default=0, max_length=10)),
                ('primary_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
